
package at.cgsit.training.api.soap.client;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserSoap", targetNamespace = "http://soap.api.training.cgsit.at/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserSoap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "message", targetNamespace = "http://soap.api.training.cgsit.at/", className = "at.cgsit.training.api.soap.client.Message")
    @ResponseWrapper(localName = "messageResponse", targetNamespace = "http://soap.api.training.cgsit.at/", className = "at.cgsit.training.api.soap.client.MessageResponse")
    @Action(input = "http://soap.api.training.cgsit.at/UserSoap/messageRequest", output = "http://soap.api.training.cgsit.at/UserSoap/messageResponse")
    public String message();

}
